remote_theme: "mmistakes/so-simple-theme"
skin: "/assets/css/skins/dark.css"
locale: en
title: "Open Source @ Sweet Side of Sweden"
description: "Sweet Side of Sweden's Open Source work."
baseurl: # the subpath of your site, e.g. "/blog"
url: "https://opensource.sweetsideofsweden.com/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "https://github.com/sweet-side-of-sweden.png" # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: false # MathJax equations, e.g. true, false (default)
  combo: # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags: # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Open Source @ Sweet Side of Sweden
  picture: https://github.com/sweet-side-of-sweden.png
  email: opensource@sweetsideofsweden.com

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/sweet-side-of-sweden/
    icon: fab fa-github-square
